research_task:
  description: >
    Conduct a thorough research about {topic}.
    Make sure to find any interesting and relevant information given the current year is 2024.
    Use advanced search tools and scraping methods to gather data from reliable sources.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}.
  agent: researcher

reporting_task:
  description: >
    Review the research findings and expand each topic into a full section for a report.
    Ensure the report is detailed and contains all relevant information.
  expected_output: >
    A comprehensive report with main topics, each with a full section of information.
    The report should be in Portuguese (PT-BR) and formatted as text embedded HTML.
  agent: reporting_analyst

fact_check_task:
  description: >
    Verify the accuracy of the research findings for {topic}.
    Cross-check information from reliable sources and ensure that all points are correct and up-to-date.
  expected_output: >
    A validation report with each point checked, indicating whether it is verified or requires correction.
  agent: fact_checker
